<?php
require_once __DIR__ . '/../../../../autoload.php';

class ClassmapClearTask extends Task
{
    protected $file;
    protected $failonerror = false;

    /**
     * classmap file
     *
     * @param  string $file
     * @return void
     */
    public function setFile($file)
    {
        touch($file);
        $this->file = realpath($file);
    }

    /**
     * if error occured, whether build should fail
     *
     * @param  bool $value
     * @return void
     */
    public function setFailonerror($value)
    {
        $this->failonerror = $value;
    }

    /**
     * init
     *
     * @return void
     */
    public function init()
    {
    }

    /**
     * main method
     *
     * @return void
     */
    public function main()
    {
        $this->log(sprintf('Clearing classmap file %s', $this->file));

        // Create a file with the class/file map.
        // Stupid syntax highlighters make separating < from PHP declaration necessary
        $content = '<' . "?php\n"
                 . "// Auto-generated by Phing, using ZF2's classmap generator\n"
                 . '// Generation time: ' . date(DATE_RFC2822) . "\n"
                 . 'return array();';

        // Write the contents to disk
        file_put_contents($this->file, $content);

        $this->log(sprintf('Cleared classmap file at %s', $this->file));
    }
}
